### ISSUE TITLE
Host system complaining

### ISSUE THREAD

**Issue by otacke** [h5p/h5p-php-library#60]
On the release version, this part of the code

https://github.com/h5p/h5p-php-library/blob/5d7b480c3b6ba41c2f27bdf06f93dfcd389cddd4/h5p.classes.php#L4025-L4032

yields

> Warning: First parameter must either be an object or the name of an existing class in /foo/h5p/h5p-php-library/h5p.classes.php on line 3893

if there's a group that contains only one item and the optional property is not set.

I think that's actually a problem with core turning a one item group from an array with one object into just an object. The default property then has to be set on the group, not on the item, in order to be used correctly by the editor. The code referenced above, however, doesn't use that one leading to the error message if the optional property is not set for the item.

**Comment by icc** [comment]
I believe this has been fixed in 70278d15f4cc59b6751eafb8b5ccefd5a89d965c, but hasn't been released yet. Are you able to confirm?

**Comment by otacke** [comment]
Ah, nice. Give me some time to upgrade an instance to the master branch and check it, please.

**Comment by otacke** [comment]
The problem remains using the master branch. If you have a one item group in semantics that has a default property, but the optional property is not set to true, you still receive the warning message.

**Comment by icc** [comment]
Ok, going to have to look into it.
